// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: control.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// nonce is echoed back verbatim so the client can match a reply to its
	// request. RTT is measured on the client from its own send/receive clock;
	// the agent's clock is informational only (agent_unix_ms).
	Nonce         int64 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         int64                  `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	AgentUnixMs   int64                  `protobuf:"varint,2,opt,name=agent_unix_ms,json=agentUnixMs,proto3" json:"agent_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *PingResponse) GetAgentUnixMs() int64 {
	if x != nil {
		return x.AgentUnixMs
	}
	return 0
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	StartedUnixMs int64                  `protobuf:"varint,2,opt,name=started_unix_ms,json=startedUnixMs,proto3" json:"started_unix_ms,omitempty"`
	Routes        []*RouteInfo           `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetStatusResponse) GetStartedUnixMs() int64 {
	if x != nil {
		return x.StartedUnixMs
	}
	return 0
}

func (x *GetStatusResponse) GetRoutes() []*RouteInfo {
	if x != nil {
		return x.Routes
	}
	return nil
}

type RouteInfo struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Target  string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Address string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// builtin reports only whether this entry is still a compiled-in default.
	// It is kept because callers already read it; provenance below is the
	// authoritative answer and can say more.
	Builtin bool `protobuf:"varint,3,opt,name=builtin,proto3" json:"builtin,omitempty"`
	// provenance says where the entry came from: a compiled-in default, the
	// operator's configuration, or something added while the agent was
	// running. A peer too old to send it leaves it empty, which a reader must
	// tolerate rather than treat as a fourth kind.
	Provenance    string `protobuf:"bytes,4,opt,name=provenance,proto3" json:"provenance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteInfo) Reset() {
	*x = RouteInfo{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteInfo) ProtoMessage() {}

func (x *RouteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteInfo.ProtoReflect.Descriptor instead.
func (*RouteInfo) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *RouteInfo) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RouteInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RouteInfo) GetBuiltin() bool {
	if x != nil {
		return x.Builtin
	}
	return false
}

func (x *RouteInfo) GetProvenance() string {
	if x != nil {
		return x.Provenance
	}
	return ""
}

type AddVhostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// host is the whole name a browser will ask for, already lowercased by the
	// caller, e.g. "grafana.server1.internal".
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// port is a port on the agent's own loopback interface, and the only thing
	// a caller may say about where traffic goes.
	//
	// It is a port and not an address on purpose. An address field would let a
	// caller name any destination the agent can reach — a unix socket carrying
	// a privileged API, a machine somewhere else on the agent's network — and
	// turning the agent into a general-purpose forwarder for whatever a caller
	// names is precisely what the route table exists to prevent. A field that
	// cannot express a destination has no edge case a validator could miss.
	Port          uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVhostRequest) Reset() {
	*x = AddVhostRequest{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVhostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVhostRequest) ProtoMessage() {}

func (x *AddVhostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVhostRequest.ProtoReflect.Descriptor instead.
func (*AddVhostRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *AddVhostRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *AddVhostRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type RemoveVhostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// host is the whole name to withdraw, as it was published.
	Host          string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveVhostRequest) Reset() {
	*x = RemoveVhostRequest{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveVhostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveVhostRequest) ProtoMessage() {}

func (x *RemoveVhostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveVhostRequest.ProtoReflect.Descriptor instead.
func (*RemoveVhostRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveVhostRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type RemoveVhostResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// host echoes the name that was withdrawn.
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// shadowed_by names a pattern that resumes serving the name now the exact
	// entry is gone, and is empty when nothing does. A withdrawal can be true and
	// still leave the name answered, at a different address, and a caller told
	// only "done" would have no way to know.
	ShadowedBy    string `protobuf:"bytes,2,opt,name=shadowed_by,json=shadowedBy,proto3" json:"shadowed_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveVhostResponse) Reset() {
	*x = RemoveVhostResponse{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveVhostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveVhostResponse) ProtoMessage() {}

func (x *RemoveVhostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveVhostResponse.ProtoReflect.Descriptor instead.
func (*RemoveVhostResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveVhostResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RemoveVhostResponse) GetShadowedBy() string {
	if x != nil {
		return x.ShadowedBy
	}
	return ""
}

type ListVhostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVhostsRequest) Reset() {
	*x = ListVhostsRequest{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVhostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVhostsRequest) ProtoMessage() {}

func (x *ListVhostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVhostsRequest.ProtoReflect.Descriptor instead.
func (*ListVhostsRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

type ListVhostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vhosts        []*VhostInfo           `protobuf:"bytes,1,rep,name=vhosts,proto3" json:"vhosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVhostsResponse) Reset() {
	*x = ListVhostsResponse{}
	mi := &file_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVhostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVhostsResponse) ProtoMessage() {}

func (x *ListVhostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVhostsResponse.ProtoReflect.Descriptor instead.
func (*ListVhostsResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{9}
}

func (x *ListVhostsResponse) GetVhosts() []*VhostInfo {
	if x != nil {
		return x.Vhosts
	}
	return nil
}

type VhostInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// host is the whole name, with its star if it is a pattern.
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// address is where the name points, as configured.
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// builtin is carried for symmetry with a route entry. No published name is
	// compiled in, so it is always false; provenance is the field that
	// distinguishes configuration from a runtime addition.
	Builtin bool `protobuf:"varint,3,opt,name=builtin,proto3" json:"builtin,omitempty"`
	// provenance says where the entry came from. A peer too old to send it leaves
	// it empty, which a reader must tolerate rather than treat as another kind.
	Provenance    string `protobuf:"bytes,4,opt,name=provenance,proto3" json:"provenance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VhostInfo) Reset() {
	*x = VhostInfo{}
	mi := &file_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VhostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VhostInfo) ProtoMessage() {}

func (x *VhostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VhostInfo.ProtoReflect.Descriptor instead.
func (*VhostInfo) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{10}
}

func (x *VhostInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *VhostInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *VhostInfo) GetBuiltin() bool {
	if x != nil {
		return x.Builtin
	}
	return false
}

func (x *VhostInfo) GetProvenance() string {
	if x != nil {
		return x.Provenance
	}
	return ""
}

type AddVhostResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// host and port echo what was actually published, after validation, so the
	// caller reports the name that really exists rather than the one it asked
	// for.
	Host          string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVhostResponse) Reset() {
	*x = AddVhostResponse{}
	mi := &file_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVhostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVhostResponse) ProtoMessage() {}

func (x *AddVhostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVhostResponse.ProtoReflect.Descriptor instead.
func (*AddVhostResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{11}
}

func (x *AddVhostResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *AddVhostResponse) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\vquiclink.v1\"#\n" +
	"\vPingRequest\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x03R\x05nonce\"H\n" +
	"\fPingResponse\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x03R\x05nonce\x12\"\n" +
	"\ragent_unix_ms\x18\x02 \x01(\x03R\vagentUnixMs\"\x12\n" +
	"\x10GetStatusRequest\"\x85\x01\n" +
	"\x11GetStatusResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12&\n" +
	"\x0fstarted_unix_ms\x18\x02 \x01(\x03R\rstartedUnixMs\x12.\n" +
	"\x06routes\x18\x03 \x03(\v2\x16.quiclink.v1.RouteInfoR\x06routes\"w\n" +
	"\tRouteInfo\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x18\n" +
	"\abuiltin\x18\x03 \x01(\bR\abuiltin\x12\x1e\n" +
	"\n" +
	"provenance\x18\x04 \x01(\tR\n" +
	"provenance\"9\n" +
	"\x0fAddVhostRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"(\n" +
	"\x12RemoveVhostRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\"J\n" +
	"\x13RemoveVhostResponse\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x1f\n" +
	"\vshadowed_by\x18\x02 \x01(\tR\n" +
	"shadowedBy\"\x13\n" +
	"\x11ListVhostsRequest\"D\n" +
	"\x12ListVhostsResponse\x12.\n" +
	"\x06vhosts\x18\x01 \x03(\v2\x16.quiclink.v1.VhostInfoR\x06vhosts\"s\n" +
	"\tVhostInfo\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x18\n" +
	"\abuiltin\x18\x03 \x01(\bR\abuiltin\x12\x1e\n" +
	"\n" +
	"provenance\x18\x04 \x01(\tR\n" +
	"provenance\":\n" +
	"\x10AddVhostResponse\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port2\xfc\x02\n" +
	"\aControl\x12;\n" +
	"\x04Ping\x12\x18.quiclink.v1.PingRequest\x1a\x19.quiclink.v1.PingResponse\x12J\n" +
	"\tGetStatus\x12\x1d.quiclink.v1.GetStatusRequest\x1a\x1e.quiclink.v1.GetStatusResponse\x12G\n" +
	"\bAddVhost\x12\x1c.quiclink.v1.AddVhostRequest\x1a\x1d.quiclink.v1.AddVhostResponse\x12M\n" +
	"\n" +
	"ListVhosts\x12\x1e.quiclink.v1.ListVhostsRequest\x1a\x1f.quiclink.v1.ListVhostsResponse\x12P\n" +
	"\vRemoveVhost\x12\x1f.quiclink.v1.RemoveVhostRequest\x1a .quiclink.v1.RemoveVhostResponseBCZAgithub.com/mauriciomem/quic-link/internal/control/proto;controlpbb\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_control_proto_goTypes = []any{
	(*PingRequest)(nil),         // 0: quiclink.v1.PingRequest
	(*PingResponse)(nil),        // 1: quiclink.v1.PingResponse
	(*GetStatusRequest)(nil),    // 2: quiclink.v1.GetStatusRequest
	(*GetStatusResponse)(nil),   // 3: quiclink.v1.GetStatusResponse
	(*RouteInfo)(nil),           // 4: quiclink.v1.RouteInfo
	(*AddVhostRequest)(nil),     // 5: quiclink.v1.AddVhostRequest
	(*RemoveVhostRequest)(nil),  // 6: quiclink.v1.RemoveVhostRequest
	(*RemoveVhostResponse)(nil), // 7: quiclink.v1.RemoveVhostResponse
	(*ListVhostsRequest)(nil),   // 8: quiclink.v1.ListVhostsRequest
	(*ListVhostsResponse)(nil),  // 9: quiclink.v1.ListVhostsResponse
	(*VhostInfo)(nil),           // 10: quiclink.v1.VhostInfo
	(*AddVhostResponse)(nil),    // 11: quiclink.v1.AddVhostResponse
}
var file_control_proto_depIdxs = []int32{
	4,  // 0: quiclink.v1.GetStatusResponse.routes:type_name -> quiclink.v1.RouteInfo
	10, // 1: quiclink.v1.ListVhostsResponse.vhosts:type_name -> quiclink.v1.VhostInfo
	0,  // 2: quiclink.v1.Control.Ping:input_type -> quiclink.v1.PingRequest
	2,  // 3: quiclink.v1.Control.GetStatus:input_type -> quiclink.v1.GetStatusRequest
	5,  // 4: quiclink.v1.Control.AddVhost:input_type -> quiclink.v1.AddVhostRequest
	8,  // 5: quiclink.v1.Control.ListVhosts:input_type -> quiclink.v1.ListVhostsRequest
	6,  // 6: quiclink.v1.Control.RemoveVhost:input_type -> quiclink.v1.RemoveVhostRequest
	1,  // 7: quiclink.v1.Control.Ping:output_type -> quiclink.v1.PingResponse
	3,  // 8: quiclink.v1.Control.GetStatus:output_type -> quiclink.v1.GetStatusResponse
	11, // 9: quiclink.v1.Control.AddVhost:output_type -> quiclink.v1.AddVhostResponse
	9,  // 10: quiclink.v1.Control.ListVhosts:output_type -> quiclink.v1.ListVhostsResponse
	7,  // 11: quiclink.v1.Control.RemoveVhost:output_type -> quiclink.v1.RemoveVhostResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
